// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysvnspgbprnsexrztqvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlzdm5zcGdicHJuc2V4cnp0cXZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzI4MzYsImV4cCI6MjA3MDUwODgzNn0.huMKTS4QQIg-pGDWafnW-kC1qeOfxxxisNV-VmoLNRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});